.github/workflows/build-and-test.yml
Cognite.Common/PeriodicScheduler.cs
Cognite.Config/Configuration.cs
ExampleExtractor/ExampleExtractor.csproj
ExampleExtractor/Program.cs
ExampleExtractor/config.yml
ExtractorUtils.Test/integration/ExtractorTest.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils.Test/unit/ChunkingTest.cs
ExtractorUtils/BaseExtractor.cs
ExtractorUtils/Cognite/CogniteDestination.cs
ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/ExtractorRunner.cs
ExtractorUtils/queues/BaseUploadQueue.cs
ExtractorUtils/queues/RawUploadQueue.cs
README.md
dotnet-extractor-utils.sln

Base class for extractors, to minimize boilerplate code when creating simple extractors.
This is probably just the first step, for live data. Ideally it should also have features designed for history, and some way to enable state-store without too much boilerplate.
This PR also adds the `PeriodicScheduler` class, which simply runs tasks with a scheduled period, which can be interrupted externally. This is something more advanced extractors often end up needing, and it creates a very nice decentralized system for reading form source systems. In this case it is used heavily in the base extractor.
This PR adds a new main example to the README, and also adds that code to a separate (working) example project.

Base extractor class

---

Cognite.Common/BlockingResourceCounter.cs
Cognite.Common/OperationScheduler.cs
Cognite.Common/SharedResourceScheduler.cs
Cognite.Common/TaskScheduler.cs
Cognite.Common/TaskThrottler.cs
ExtractorUtils.Test/unit/SchedulerTest.cs

A fairly abstract construct that I nonetheless ended up needing several times in the OPC-UA extractor and decided to add here, as part of an effort to reduce code duplication in OPC-UA. If it doesn't fit I can just add it to the extractor instead, but I think it is sufficiently general that it doesn't hurt to keep it here.
The idea is that it's a sort of producer-consumer scheduler, where a generic list of items are consumed. Each item may need to be run several times, and may produce a new list of child items to consume.
An example of this is exploring a hierarchy, but also reading history (in that case no new nodes are discovered, but this is still a useful construct).
In addition, it contains a system to share capacity. In OPC-UA this is a system of continuation points, but it could …

Task scheduler

---

Cognite.Extensions/Cognite.Extensions.csproj
Cognite.Extensions/TimeSeries/DataPointExtensions.cs
ExtractorUtils/Cognite/CogniteDestination.cs
ExtractorUtils/Configuration/BaseConfig.cs
ExtractorUtils/config/config.example.yml

The default value and common in config.example.yml is based on some research done while writing this for the SDK. Turns out you need a fairly large number of datapoints before it is worthwhile. This feature counts the number of datapoints (not really the number of bytes, we could count lengths of all strings but I'm uncertain of how much that could cost), and decides on whether or not to use gzip based on a configurable limit.

Add option to automatically gzip datapoints

---

Cognite.Extensions/Assets/AssetExtensions.cs
Cognite.Extensions/Assets/AssetResultHandlers.cs
Cognite.Extensions/Assets/AssetSanitation.cs
Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/Events/EventExtensions.cs
Cognite.Extensions/Events/EventResultHandlers.cs
Cognite.Extensions/Events/EventSanitation.cs
Cognite.Extensions/LoggerExtensions.cs
Cognite.Extensions/Sequences/SequenceExtensions.cs
Cognite.Extensions/Sequences/SequenceResultHandlers.cs
Cognite.Extensions/Sequences/SequenceSanitation.cs
Cognite.Extensions/TimeSeries/DataPointExtensions.cs
Cognite.Extensions/TimeSeries/DataPointResultHandlers.cs
Cognite.Extensions/TimeSeries/DataPointSanitation.cs
Cognite.Extensions/TimeSeries/TimeSeriesExtensions.cs
Cognite.Extensions/TimeSeries/TimeSeriesResultHandlers.cs
Cognite.Extensions/TimeSeries/TimeSeriesSanitation.cs
ExampleExtractor/Program.cs
ExtractorUtils.Test/integration/SequenceIntegrationTest.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils.Test/unit/CogniteResultTests.cs
ExtractorUtils.Test/unit/SanitationTest.cs
ExtractorUtils/Cognite/CogniteDestination.cs

The original use of CogniteError and CogniteResult was just for assets/timeseries/events, and there it worked well enough. Now with more types, the use of `object` makes the system difficult to use. This PR changes that so that CogniteError now takes a type parameter, and also standardizing what an error represents.
This PR also fixes a few issues with logging, and adds a "ThrowOnError" method to CogniteResult so that errors can be translated back into exceptions.

Refactor errors

---

ExtractorUtils.Test/integration/RawIntegrationTest.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils.Test/unit/CdfRawTest.cs
ExtractorUtils.Test/unit/DatapointsTest.cs
ExtractorUtils.Test/unit/EventTest.cs
ExtractorUtils/BaseExtractor.cs
ExtractorUtils/queues/BaseUploadQueue.cs

This has caused issues in the past. Calling code asynchronously in Dispose() can cause a deadlock in some circumstances. Using IAsyncDisposable (hopefully) avoid this.

Use IAsyncDisposable where relevant

---

ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/ExtractorRunner.cs

This is useful in cases where there the extractor is designed to run without config file, or if the config is obtained from elsewhere somehow.

Add option to pass pre-created config object

---

Cognite.Common/PeriodicScheduler.cs
ExtractorUtils.Test/unit/ChunkingTest.cs

Improved ability to handle errors in PeriodicScheduler. It was too difficult to know whether a task existed or not, and what to do about it. This adds the option to pass tasks without name, and check whether a task with a given name exists.
It also fixes a bug where thrown errors were not properly reported.

Scheduler error handling

---

ExtractorUtils.Test/integration/ExtractorTest.cs
ExtractorUtils/BaseExtractor.cs
ExtractorUtils/ExtractionRun.cs
ExtractorUtils/ExtractorRunner.cs

This required some changes to the startup, but the final solution is generally better. Now the extractor itself is responsible for the run, and not the ExtractorRunner Run method. This is more general and useful if users don't want to use the Run method.

Optionally report success on startup of extractor run

---

Cognite.Extensions/TimeSeries/DataPointExtensions.cs
Cognite.Logging/Logger.cs
ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/ExtractorRunner.cs

This is useful for testing, or for adding other logging destinations. To make this even easier, the method building LoggerConfiguration is also separated so that it can be called externally.

Option to pass method for configuring logger

---

Cognite.Extensions/CogniteResult.cs
ExtractorUtils.Test/unit/CogniteResultTests.cs

Useful for reporting errors per element, which is a big part of the purpose of the whole error system.

Utility method to group by skipped elements

---

Cognite.Common/ConfigurationException.cs
Cognite.Config/Cognite.Configuration.csproj
Cognite.Config/Configuration.cs
Cognite.Extensions/Authenticator.cs
Cognite.Extensions/Cognite.Extensions.csproj
Cognite.Extensions/MsalAuthenticator.cs
ExtractorUtils.Test/CDFTester.cs
ExtractorUtils.Test/unit/ConfigurationTest.cs
ExtractorUtils/Configuration/BaseConfig.cs
ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/ExtractorRunner.cs
ExtractorUtils/ExtractorUtils.csproj
docfx_project/tutorials/authentication.md
docfx_project/tutorials/toc.yml

Make the authenticator available and usable from just the Cognite.Extensions library, to make it possible to use the utils for just authentication without pulling libraries for config, metrics, state, etc.
Also add documentation for how to do this.

Move authenticator

---

Cognite.Common/CommonUtils.cs
Cognite.Common/PeriodicScheduler.cs
Cognite.Common/TaskThrottler.cs
ExtractorUtils.Test/unit/ChunkingTest.cs

Slightly more clever implementation of this functionality, if we schedule 10 items per 1000 seconds, we really want to run one about every 100 seconds, not 10 in the first 10 seconds and 0 in the remaining time. This makes a few small changes to help with this.

Improve limiting by items per time unit

---

Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/LoggerExtensions.cs

Better message in CogniteErrorException.
Method to log CogniteResult without a result type.

Minor improvements to logging

---

Cognite.Extensions/Assets/AssetExtensions.cs
Cognite.Extensions/Assets/AssetUpdateSanitation.cs
Cognite.Extensions/Cognite.Extensions.csproj
Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/TimeSeries/TimeSeriesExtensions.cs
Cognite.Extensions/TypeExtensions.cs
ExtractorUtils.Test/integration/AssetIntegrationTest.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils/Cognite/CogniteDestination.cs

With error handling on updates, we can implement upserts. The challenge is mostly just only processing updates for items which successfully were found or created.

[CDF-14262] Upsert logic

---

ExtractorUtils/Cognite/DestinationUtils.cs
ExtractorUtils/Configuration/BaseConfig.cs
ExtractorUtils/config/config.example.yml

I don't really like adding this, but this is a frequent issue with extractors, and there is no native way to work around it.
It is necessary to do this twice, since the best way to do it is only available on 2.1. Most users will be using a 2.1 compatible version, so this isn't a big problem. On 2.0 they need to call a method explicitly to use this.

[CDF-14308] Configuration to ignore SSL-certificate issues

---

ExtractorUtils/ExtractionRun.cs

It isn't always intuitive for users that they need this capability, and we currently don't use it. We should just log a warning if retrieving fails.

[CDF-14313] Allow runs to be reported when missing read cap

---

Cognite.Extensions/Assets/AssetExtensions.cs
Cognite.Extensions/Assets/AssetResultHandlers.cs
Cognite.Extensions/Assets/AssetUpdateResultHandlers.cs
Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/Events/EventExtensions.cs
Cognite.Extensions/Sequences/SequenceExtensions.cs
Cognite.Extensions/Sequences/SequenceResultHandlers.cs
Cognite.Extensions/TimeSeries/DataPointResultHandlers.cs
Cognite.Extensions/TimeSeries/TimeSeriesExtensions.cs

We shouldn't really throw exceptions from these, as we expect them to return error objects. We still treat these errors as fatal.

Catch errors when retrieving in methods with error handling

---

Cognite.Extensions/Assets/AssetExtensions.cs
Cognite.Extensions/Assets/AssetResultHandlers.cs
Cognite.Extensions/Assets/AssetSanitation.cs
Cognite.Extensions/Assets/AssetUpdateResultHandlers.cs
Cognite.Extensions/Assets/AssetUpdateSanitation.cs
Cognite.Extensions/CdfMetrics.cs
Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/Events/EventResultHandlers.cs
Cognite.Extensions/Events/EventSanitation.cs
Cognite.Extensions/Sanitation.cs
Cognite.Extensions/Sequences/SequenceResultHandlers.cs
Cognite.Extensions/Sequences/SequenceSanitation.cs
Cognite.Extensions/TimeSeries/TimeSeriesResultHandlers.cs
Cognite.Extensions/TimeSeries/TimeSeriesSanitation.cs
Cognite.Extensions/TimeSeries/TimeSeriesUpdateResultHandlers.cs
Cognite.Extensions/TimeSeries/TimeSeriesUpdateSanitation.cs
Cognite.Extensions/TypeExtensions.cs
ExtractorUtils.Test/integration/SequenceIntegrationTest.cs
ExtractorUtils.Test/unit/CogniteResultTests.cs
ExtractorUtils.Test/unit/SanitationTest.cs

Code to generalize the CleanFromError and CleanRequest methods. These contain a lot of common logic in most cases, so we can create a common base method and call that, reducing complexity and code duplication.
This could be made easier with native SDK methods for getting Identity from the DTOs.

Common handlers

---

Cognite.Extensions/LoggerExtensions.cs

This kind of log can be very frequent, and we should avoid creating useless log-lines.

Remove unnecessary logging for results

---

ExtractorUtils/ExtractorRunner.cs

This one is really ugly. It is compiler dependent, and probably _optimization level dependent_ Essentially what happens is that the compiler can decide to inline the continuation after calling `CancellationTokenSource.Cancel()`. so calling "remove" on the event handler happens inside the event handler itself, and deadlocks. Running it in a separate task should fix the problem, but this one is really unpleasant.

Fix unpleasant deadlock in ExtractorRunner

---

ExtractorUtils/ExtractionRun.cs
ExtractorUtils/ExtractorRunner.cs

This helps for extractors that are not continuous. We may want these to restart on missing config, but not otherwise.

Separate logic for restarting on config and on error

---

Cognite.Common/TaskThrottler.cs

We waited for tasks to complete inside the loop, which meant that if cancelation of the loop was requested while it was in the part of the code _after_ that (for example waiting on the mutex), they would never be awaited.
There is no real reason to wait inside the loop, we can just wait outside it, it is effectively the same.

Fix race condition in TaskThrottler

---

Cognite.Testing/Cognite.Testing.csproj

Apparently if you include a dependency to xunit then magically your package must set IsPackable.

Fix testing build

---

Cognite.Metrics/MetricsService.cs
ExampleExtractor/ExampleExtractor.csproj
ExampleExtractor/Program.cs
ExtractorUtils/Cognite/DestinationUtils.cs

This is caused by polly retries triggering during dispose, which apparently can cause issues. There might be some underlying issue, but I couldn't figure it out.

Suppress object disposed errors on extractor close

---

Cognite.Extensions/Cognite.Extensions.csproj
ExampleExtractor/Program.cs
ExtractorUtils.Test/ExtractorUtils.Test.csproj
ExtractorUtils.Test/unit/CommandLineTest.cs
ExtractorUtils/CommandLine/AttributeBinder.cs
ExtractorUtils/CommandLine/CommandLineOptionAttribute.cs
ExtractorUtils/ExtractorUtils.csproj

We've made command line interfaces like this for several extractors. The System.CommandLine library broke the old way of doing it, and it was also quite verbose. This adds a simple attribute-based system for defining flat command line interfaces.

Command line utility

---

Cognite.Testing/TestLogging.cs

This was just missing, verbose is too high for most use cases.

Add option to reduce test verbosity

---

Cognite.Extensions/DeleteError.cs
Cognite.Extensions/TimeSeries/DataPointExtensions.cs
ExtractorUtils.Test/unit/DatapointsTest.cs

We once needed this, since timeseries were not immediately consistent, but that is no longer the case, and this adds additional complexity that we don't need.

Remove verification of datapoint deletes

---

Cognite.Extensions/TimeSeries/DataPointExtensions.cs

Also remove the VerifyDataPointsDeletion method.
The issue was that we want to check whether creating timeseries failed, but we looked at the wrong result. Simple fix.

Fix InsertAsyncCreateMissing

---

Cognite.Common/Cognite.Common.csproj
Cognite.Common/PeriodicScheduler.cs
Cognite.Config/Configuration.cs
Cognite.Extensions/Cognite.Extensions.csproj
Cognite.Logging/Cognite.Logging.csproj
Cognite.Metrics/Cognite.Metrics.csproj
ExampleExtractor/Program.cs
ExampleExtractor/config.yml
ExtractorUtils.Test/CDFTester.cs
ExtractorUtils.Test/ExtractorUtils.Test.csproj
ExtractorUtils.Test/integration/ExtractorTest.cs
ExtractorUtils.Test/integration/RemoteConfigTest.cs
ExtractorUtils/BaseExtractor.cs
ExtractorUtils/Configuration/BaseConfig.cs
ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/Configuration/RemoteConfig.cs
ExtractorUtils/ExtractorRunner.cs
ExtractorUtils/ExtractorUtils.csproj

Support for remote configuration files in the .NET extractor utils.
As demonstrated in the ExampleExtractor, this can be quite simple to use: just inject it optionally in the constructor, then pass it to BaseExtractor, and optionally configure it to refresh with a fixed period.
Unlike the python utils, we make no attempts at handling new detected configuration files, beyond triggering an event, which can stop the extractor or make some other extractor specific change.
The _volume_ of code is unfortunately quite large, just because this feature is involved in many parts of the framework.

Remote config

---

Cognite.Common/HighAvailability.cs
ExtractorUtils.Test/unit/RawHighAvailabilityTest.cs
ExtractorUtils/HighAvailability/HighAvailabilityManager.cs
ExtractorUtils/HighAvailability/RawHighAvailabilityManager.cs
ExtractorUtils/HighAvailability/RedisHighAvailabilityManager.cs

It takes a bit long now, there are two reasons:
- Instead of reusing uploaded state, we re-download the state and use that, which may be outdated.
- We wait on startup, unnecessarily.

Improve HA startup time

---

Cognite.Extensions/Cognite.Extensions.csproj
ExtractorUtils.Test/integration/RemoteConfigTest.cs
ExtractorUtils/Configuration/RemoteConfig.cs

In order to move extpipe configs to production.

Bump cognite sdk

---

ExtractorUtils/ExtractionRun.cs
ExtractorUtils/config/config.example.yml

It is now possible to create a single common base config file for remote python and .NET extractors.

Add alias for pipeline-id, to align with python utils

---

ExtractorUtils/Configuration/RemoteConfig.cs

This occurs if the Cognite field is a subtype of CogniteConfig (which we do support), and no cognite field is created in the remote config.

[DOG-367] Fix issue overriding fields in subtype

---

Cognite.Extensions/Authenticator.cs
ExtractorUtils.Test/integration/AuthIntegrationTest.cs
ExtractorUtils.Test/unit/CogniteTest.cs
ExtractorUtils/Cognite/DestinationUtils.cs
ExtractorUtils/config/config.example.yml

This ensures that any config with `tenant` set will always use the `MSALAuthenticator` and that with `token-url` will use the basic `Authenticator` implementation. This renders `idp-authentication.implementation` deprecated.

feat: automatic authenticator implied

---

ExampleExtractor/config.yml
ExampleExtractor/full_config.schema.json
schema/base_config.schema.json
schema/cognite_config.schema.json
schema/high_availability.schema.json
schema/logger_config.schema.json
schema/metrics_config.schema.json
schema/state_store_config.schema.json

They make it so that we're unable to extend them (which makes sense). Any types which we intend users to extend we drop unevaluatedProperties from. This still works because we just let users add those directly on their own properties if they use them directly.
See ExampleExtractor/full_config.schema.json for an example, we put unevaluatedProperties on the top level, and inside each externally referenced property, indicating that we won't extend them further.
In theory you could reference properties from other types directly, and extending those would work poorly, but that's a sacrifice we can make.

Remove top level unevaluatedProperties

---

Cognite.Config/Configuration.cs
ExtractorUtils.Test/unit/ConfigurationTest.cs

This PR updates YAML deserializer to support null value parsing. Possible null representations are meant to cover the options from https://yaml.org/type/null.html.

Add support for parsing null values from YAML

---

Cognite.Common/Retry.cs
ExtractorUtils.Test/unit/RetryTest.cs

The number of maximum retries should be equal to max-retries, and the logged attempt number should start at 1.

Fix retry counting

---

ExampleExtractor/Program.cs
ExtractorUtils/ExtractorRunner.cs

The extractor would not properly enable remote config after restarting, since it kept the previous config. This meant that config changes were not picked up. This should fix that, making it so that if we enable remote config once, it is enabled in all future iterations as well.

Reload remote config after restart

---

Cognite.Extensions/DataSetExtensions.cs
ExtractorUtils.Test/CDFTester.cs
ExtractorUtils.Test/integration/AuthIntegrationTest.cs
ExtractorUtils.Test/integration/RawHighAvailabilityTest.cs
ExtractorUtils.Test/integration/UtilsIntegrationTest.cs
ExtractorUtils.Test/unit/DatapointsTest.cs
ExtractorUtils/Configuration/BaseConfig.cs

In order to align with python utils, it's nice to have a config class with logic for fetching data set ID.

Add config class for data sets

---

ExtractorUtils/ExtractorRunner.cs

The alternative produces some very unhelpful error messages

Include inner error when logging config errors

---

Cognite.Common/CogniteTime.cs
Cognite.Extensions/CogniteUtils.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils.Test/unit/CogniteTimeTest.cs
ExtractorUtils.Test/unit/DatapointsTest.cs
ExtractorUtils.Test/unit/SanitationTest.cs

CDF allows negative unix timestamps now, and behavior in the utils should reflect that.

Update allowed ranges for unix timestamps

---

Cognite.Extensions/Assets/AssetExtensions.cs
Cognite.Extensions/CogniteResult.cs
Cognite.Extensions/Events/EventExtensions.cs
Cognite.Extensions/Sequences/SequenceExtensions.cs
Cognite.Extensions/TimeSeries/DataPointExtensions.cs
Cognite.Extensions/TimeSeries/TimeSeriesExtensions.cs
ExtractorUtils/queues/BaseUploadQueue.cs
ExtractorUtils/queues/EventUploadQueue.cs
ExtractorUtils/queues/RawUploadQueue.cs
ExtractorUtils/queues/TimeSeriesUploadQueue.cs

- Better handle fatal errors when retrying.
- Avoid mixing sync and async in BaseUploadQueue
- Return the list of failed items to the user, when possible.
- Make the BaseUploadQueue constructor public

Upload queue improvements

---

Cognite.Extensions/Authenticator.cs
Cognite.Extensions/MsalAuthenticator.cs
Cognite.Testing/ConsoleWrapper.cs

They are actually a little racy, this should help make them less prone to duplicate token requests.

Thread-proof authenticators

---

Cognite.Common/ListOrSpaceSeparated.cs
Cognite.Config/Configuration.cs
Cognite.Extensions/Authenticator.cs
Cognite.Extensions/MsalAuthenticator.cs
ExtractorUtils.Test/unit/ConfigurationTest.cs
ExtractorUtils/Cognite/DestinationUtils.cs
ExtractorUtils/config/remote_config.yml

Create a config file that can be used for remote config. This also makes a few changes to make that more possible.
- Allow scopes to be configured either as a list of strings, or as space separated strings.
- Allow an empty "certificate" block
- Improve handling of empty values.

Better remote configuration

---

.github/workflows/build-and-test.yml
Cognite.Common/Cognite.Common.csproj
Cognite.Config/Cognite.Configuration.csproj
Cognite.Config/Configuration.cs
Cognite.Config/KeyVault.cs
Cognite.Config/VersionedConfig.cs
Cognite.Extensions/Cognite.Extensions.csproj
Cognite.Logging/Cognite.Logging.csproj
Cognite.Metrics/Cognite.Metrics.csproj
Cognite.StateStorage/Cognite.StateStorage.csproj
Cognite.Testing/Cognite.Testing.csproj
ExtractorUtils.Test/ExtractorUtils.Test.csproj
ExtractorUtils.Test/unit/ConfigurationTest.cs
ExtractorUtils/Configuration/Configuration.cs
ExtractorUtils/ExtractorUtils.csproj

Designed to be as similar as possible to the python version, which required some work.
Among other things, it required a custom enum serializer to let us have aliases. This is a neat addition anyway.
This also makes the snk path relative, since solutiondir often doesn't exist.

KeyVault support

---

ExtractorUtils/ExtractionRun.cs

This fixes that and also makes it reentrant, which might be handy.

ExtractorRun contained a silly deadlock

---

Cognite.Config/Configuration.cs

YamlDotNet handles this poorly, imo, and we pretty much have to do this to not have users need to try/catch all over the place.

Do not throw on type converter duplicates

---

.github/workflows/bump-version.yml

Update version of the code-sign-action before upcoming signing key rotation.
Changes:
* Bump version of the code-sign-action.
* Add keypair alias variable which was hard coded in the previous versions.

[SEC-3551] Update version of the code-sign-action

---

ExtractorUtils/Configuration/RemoteConfig.cs

Looks like when the extractors do not have write access to the remote config local buffer path, they get stuck in a broken state. This should address that.

Avoid broken state on from unwritable local config buffer

---

Cognite.Extensions/Authenticator.cs
Cognite.Extensions/MsalAuthenticator.cs
Cognite.Extensions/Unstable/AuthenticatorConfig.cs
ExtractorUtils.Test/integration/IDMTimeSeriesIntegrationTest.cs
ExtractorUtils.Test/integration/TimeSeriesIntegrationTest.cs
ExtractorUtils.Test/unit/CogniteTest.cs
ExtractorUtils.Test/unit/DatapointsTest.cs
ExtractorUtils.Test/unit/EventTest.cs
ExtractorUtils.Test/unit/Unstable/ConnectionConfigTests.cs
ExtractorUtils/Cognite/CogniteClientExtensions.cs
ExtractorUtils/Cognite/CogniteDestination.cs
ExtractorUtils/Cognite/CogniteDestinationWithIDM.cs
ExtractorUtils/Cognite/DestinationUtils.cs
ExtractorUtils/Unstable/Configuration/BaseConfig.cs
ExtractorUtils/Unstable/Configuration/Cognite.cs
ExtractorUtils/Unstable/Configuration/Connection.cs
ExtractorUtils/Unstable/DestinationUtilsUnstable.cs
ExtractorUtils/queues/EventUploadQueue.cs

Defines `ConnectionConfig` and some utils related to this. Lots more to do before we can actually use this for anything.

Start work on the unstable module

---

Cognite.Extensions/Cognite.Extensions.csproj
ExtractorUtils.Test/unit/Unstable/CheckInWorkerTests.cs
ExtractorUtils.Test/unit/Unstable/TaskSchedulerTest.cs
ExtractorUtils/Unstable/Tasks/CheckInWorker.cs
ExtractorUtils/Unstable/Tasks/Errors.cs
ExtractorUtils/Unstable/Tasks/ExtractorTaskScheduler.cs
ExtractorUtils/Unstable/Tasks/Task.cs

Class that periodically writes CheckIns to the integrations API.
Includes some slightly clever logic to deal with issues if there are more than 1000 task updates or errors in a single request, hopefully avoiding issues where we get sporadic 400s due to weird ordering on the task requests.

CheckIn worker

---

Cognite.Config/Configuration.cs
ExtractorUtils.Test/unit/Unstable/CheckInWorkerTests.cs
ExtractorUtils.Test/unit/Unstable/ConnectionConfigTests.cs
ExtractorUtils.Test/unit/Unstable/TaskSchedulerTest.cs
ExtractorUtils/Unstable/Configuration/ConfigSource.cs
ExtractorUtils/Unstable/DestinationUtilsUnstable.cs

Just a simple utility class containing code for fetching configs from CDF. It's maybe a bit early for this, since I still don't have a perfectly clear idea of how it's going to be used, but most of the logic here makes sense in general, and is a foundation for future work.

Add utility for config loading

---

ExtractorUtils.Test/unit/Unstable/BaseExtractorTest.cs
ExtractorUtils.Test/unit/Unstable/CheckInWorkerTests.cs
ExtractorUtils.Test/unit/Unstable/TaskSchedulerTest.cs
ExtractorUtils/Unstable/BaseExtractor.cs
ExtractorUtils/Unstable/Tasks/CheckInWorker.cs
ExtractorUtils/Unstable/Tasks/Errors.cs
ExtractorUtils/Unstable/Tasks/ExtractorTaskScheduler.cs

First take on a new base extractor class. Some more work goes into this in the next step, adding startup reporting and integrating things a bit more tightly, but this is a nice first draft that contains some of the core logic.
The base extractor has a few roles, currently:
- It contains the config object, in the future it will also handle changes to config revision and restart.
- It acts as an error reporter, for raw errors.
- It manages "monitored tasks", which are essentially just C# Tasks. The idea is that if something fails in a background process, this needs to be properly reported to the extractor so that it can take appropriate action. Background tasks have a name, can be cancelled independently, and can be expected to end or not, so if a task ends without an error, the extractor …

Base extractor

---

ExtractorUtils.Test/unit/Unstable/CheckInWorkerTests.cs
ExtractorUtils/Unstable/Tasks/CheckInWorker.cs

This is necessary step, making the checkin worker capable of calling some callback to inform the runtime and/or extractor (not sure yet) that a new config revision has been produced, and that the extractor should restart.
It will be up to the outer loop to decide whether the config changes are significant enough to warrant a change (if we decide to go that way).
I also improved the checkin worker a bit in general, making it a bit more resilient to cancellation.
It's quite important that errors aren't lost when the extractor shuts down, so we need to make sure that any errors that failed to write or weren't written are kept for a future checkin.

Improve the checkin worker a bit, add a callback for config changes

---

Cognite.Extensions/Cognite.Extensions.csproj
ExtractorUtils.Test/unit/Unstable/BaseExtractorTest.cs
ExtractorUtils.Test/unit/Unstable/CheckInWorkerTests.cs
ExtractorUtils.Test/unit/Unstable/TaskSchedulerTest.cs
ExtractorUtils/Unstable/BaseExtractor.cs
ExtractorUtils/Unstable/Tasks/CheckInWorker.cs
ExtractorUtils/Unstable/Tasks/Errors.cs
ExtractorUtils/Unstable/Tasks/ExtractorTaskScheduler.cs
ExtractorUtils/Unstable/Tasks/Task.cs

Final part of startup reporting. This ensures that we actually send the startup request before we report _any_ checkins, thus avoiding inconsistent state in CDF, even if the extractor runs offline for some time before being able to report startup.
The ability to run offline is opt-in, so the checkin worker can be configured to crash if we cannot connect to CDF.

Report startup

---

ExtractorUtils/Cognite/CogniteClientExtensions.cs

It's nice to have an endpoint we can call to check if CDF is actually available at all, but currently this means that extractors require groups:list and projects:list, which isn't ideal. This makes that check optional.
It is enabled by default for backwards compatibility.

Make checking the project optional

---

renovate.json

This should help avoid noise and make it possible to actually get these PRs through risk review.

Only auto-update renovate PRs if they are conflicting with master

---

ExtractorUtils.Test/CDFTester.cs
ExtractorUtils.Test/integration/IDMTimeSeriesIntegrationTest.cs

This was causing schema lock conflicts and failing the tests. Instead just get the space ID when needed.

Avoid upserting spaces unnecessarily in tests

---

Cognite.Extensions/Authenticator.cs

CogIdp doesn't support sending the client secret as a form-encoded parameter. This is the preferred method anyway.
We keep the old way of doing it, to avoid regressions.
Also improve logging a bit, potentially extracting request ID.

Use bearer token auth in the authenticator

---

Cognite.Extensions/Assets/AssetResultHandlers.cs
Cognite.Extensions/Assets/AssetUpdateResultHandlers.cs

Asset error handling has been changed (improvements, largely), which broke the tests that were a little fragile. This improves the checks and actually avoids a potential error that required extra completion.

Fix asset error handling

---

ExtractorUtils.Test/unit/Unstable/TaskSchedulerTest.cs
ExtractorUtils/Unstable/BaseExtractor.cs
ExtractorUtils/Unstable/Runtime/Builder.cs
ExtractorUtils/Unstable/Tasks/ExtractorTaskScheduler.cs

Four minor fixes to the unstable module:
- Treat InfiniteTimeSpan as infinite when scheduling tasks.
- Pass the correct cancellation token to `InitConfigSource`, this was causing the extractor to hang if you tried to cancel it while it was failing due to missing connection config or the like.
- Truncate extractor version. While extractor versions aren't longer than 32 characters, for local development or dev builds they can sometimes include revision info. The limit on the API is 32 chars.
- Properly handle task scheduler cancellation. When the scheduler shuts down we do want to report that tasks have ended. I also changed it so we report a warning here, not a fatal failure, since that seems a bit strong. We should somehow report that the task didn't properly shut down, however.
I have a …

Unstable fixes

---

Cognite.Common/CommonUtils.cs
Cognite.Common/PeriodicScheduler.cs
Cognite.Testing/TestUtils.cs
ExtractorUtils.Test/unit/ChunkingTest.cs
ExtractorUtils.Test/unit/SchedulerTest.cs
ExtractorUtils.Test/unit/Unstable/BaseExtractorTest.cs
ExtractorUtils/Unstable/BaseExtractor.cs
ExtractorUtils/Unstable/Tasks/ExtractorTaskScheduler.cs

Required some refactoring and new features in the scheduler, but I think the result is pretty good. There's no real reason to have _two_ of these, and this way it's possible to use the "periodic" features on the periodic scheduler directly from extractors, which we do a fair bit, simplifying migration.

Use periodic scheduler in unstable base extractor
